apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebappcontainer
          image: reddyvarisrinu95/maven-web-application:1.0
          ports:
            - containerPort: 8080
          resources:

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mavenwebappsvc
# spec:
#   selector:
#     app: mavenwebapp
#   type: Nodeport
#   ports:
#   - port: 80
#     targetPort: 8080
