apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: default
spec:
  selector:
    app: mavenwebapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    